# This configuration was used Ebert to review the ajosg/68kDisassembler repository
# on 8c7b5012972990e4c3298396c8efb5d643a97ac7.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://docs.ebertapp.io/configuration and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  grep:
    enabled: true
    config:
      patterns:
        todo-left:
          pattern: (TODO|TO-DO)
          annotation: "TODO left in commit."
          categories:
            - "Bug Risk"
          path_patterns:
            - "**/*.X68"
        bad-movem:
          pattern: (MOVEM\.(B|W|L)\s+-\(SP\),)|(MOVEM\.(B|W|L)\s+[A-Z0-9\/\-]+,\(SP\)\+)
          annotation: "INVALID MOVEM. Make sure MOVEM has either (SP)+,registers or register,-(SP)"
          categories:
            - "Bug Risk"
          path_patterns:
            - "**/*.X68"
        toobig_add:
          pattern: ADD\.(B|W|L)\s+#[0-8],
          annotation: "Use ADDQ for constants 1-8"
          categories:
            - "Performance"
          path_patterns:
            - "**/*.X68"
        toobig_sub:
          pattern: SUB\.(B|W|L)\s+#[0-8],
          annotation: "Use SUBQ for constants 1-8"
          categories:
            - "Performance"
          path_patterns:
            - "**/*.X68"
        lowercase_label1:
          pattern: ^[A-Z][a-z:]+
          annotation: "Make sure all labels are uppercase."
          categories:
            - "Style"
            - "Bug Risk"
          path_patterns:
            - "**/*.X68"
        lowercase_label2:
          pattern: ^[a-z:]+
          annotation: "Make sure all labels are uppercase."
          categories:
            - "Style"
            - "Bug Risk"
          path_patterns:
            - "**/*.X68"
        label_start:
          pattern: ^\s+(\.|[A-Za-z_\.])+:
          annotation: "Make sure all labels start at the beginning of the line."
          categories:
            - "Style"
          path_patterns:
            - "**/*.X68"
        divorced_label:
          pattern: (?m)[A-Z\._]+:(\s+(;|\*).+|\s+)(\n|\r)
          annotation: "Make sure all labels have code on the same line. Don't put labels between empty lines."
          categories:
            - "Bug Risk"
          path_patterns:
            - "**/*.X68"
        buggy_move:
          pattern: MOVE\.L\s+#(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31),D(0|1|2|3|4|5|6|7)
          annotation: "A MOVE.L operation with direct data going into a data register with the direct data being less than 5 bits causes the EASY68k to perform a MOVEQ instead of a MOVE.L"
          categories:
            - "Compatibility"
            - "Bug Risk"
exclude_paths:
- Docs

